[package]
name = "end-to-end-tests"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
george-ai = { version = "0.1.0", path = "../george" }
dotenv = "0.15.0"